module.exports = [
  "Fighter",
  "Strike aircraft",
  "Bomber",
  "Attack helicopter",
  "Utility helicopter",
  "Medium tank",
  "Light tank",
  "Heavy tank",
  "SPAA",
  "Tank destroyer",
  "Battleship",
  "Heavy cruiser",
  "Light cruiser",
  "Destroyer",
  "Battlecruiser",
  "Boat",
  "Heavy boat",
  "Barge",
  "Frigate",
];
